### ISSUE TITLE
Backend Structure Ideas

### ISSUE THREAD

**Issue by ezriwhite** [calendar-gang/tar-heel-calendar#16]
# per user 
- user info (username, password ...) 
- list of one time events
- list of recurring events
- list of tasks
- personalized categories (this will be a later step i think)
- completed task counter/ score ( we had talked about incentivizing completing tasks) 

# events
I think these could be just one object with a boolean value for isRecurring though, but either way the user should have separate lists of the one time and recurring events?

## per one time event 
- title
- location
- description
- *date*
- start time
- end time (or length)
-  category (start as an int? -> corresponds with color)

## per recurring time event 
- title
- location
- description
- *dates*
- start time
- end time (or length)
-  category (start as an int? -> corresponds with color)

# tasks
- description
- isCompleted
- isCurrent (this field would be for determining which tasks to have shown on the current tasklist)

**Comment by eric-unc** [comment]
Right now I only have two tables:
```sql
CREATE TABLE IF NOT EXISTS `users` (
	`username` CHAR(100) NOT NULL COLLATE 'utf8_general_ci',
	`email` CHAR(100) NOT NULL COLLATE 'utf8_general_ci',
	`firstname` CHAR(100) NOT NULL COLLATE 'utf8_general_ci',
	`lastname` CHAR(100) NOT NULL COLLATE 'utf8_general_ci',
	`password` VARCHAR(256) NOT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`username`) USING BTREE,
	INDEX `email` (`email`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `tokens` (
    `token` CHAR(60) NOT NULL COLLATE 'utf8_general_ci',
    `username` CHAR(100) NOT NULL COLLATE 'utf8_general_ci',
    `whengen` TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    PRIMARY KEY (`token`) USING BTREE,
    CONSTRAINT `username`
        FOREIGN KEY(`username`) REFERENCES `users` (`username`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
```

(This SQL is partially auto-generated by HeidiSQL so there may be some unnecessary syntax but it does what you would expect it to.)

The `user` table cannot have a list of events or anything like that, rather the `events` table and other such tables will have a `user` column.

I think I can move forward with most of this although I don't know how to move forward with recurring events. It will depend _how_ it recurs: daily, monthly, once a week? There should probably be some kind of type system for that. Anyway I look at this stuff later today.

**Comment by eric-unc** [comment]
Reopening this since tasks are not yet done, and there are perhaps improvements to be made.
