### ISSUE TITLE
Signup extension

### ISSUE THREAD

**Issue by eric-unc** [calendar-gang/tar-heel-calendar#8]
Hey @torihoffmann, the login/register buttons look good! I'm working on the backend right now and I think the register part should be extended, however. As I work on the backend, I'm documenting it (API documentation is required and I think it will be more helpful for programming on the frontend than trying to read my messy code). You can see my current documentation for the register endpoint [here](https://github.com/calendar-gang/tar-heel-calendar/blob/backend/docs/register.md). Basically I think that the registration should ask for a bit more, specifically along with the username and password, a firstname/lastname and an email. Maybe I could get rid of the firstname/lastname requirement but I think the email is pretty standard. In addition, some input validation will be needed as described in the documentation (just looking at lengths of characters, you may want to do some basic regex to see if the email looks somewhat valid).

**Comment by torihoffmann** [comment]
Okay perfect! I went ahead and updated the sign up and the login sheets to include that and just look a little prettier lol. I used regex to determine if an inputted password is valid. As of now I just have an alert going off if it is invalid and the edit form will refuse to toggle till a valid password is given. I used refs to access the password input and strict mode does not seem to love that. It works perfectly fine but if you know of a better way feel free to change it or lmk!

**Comment by eric-unc** [comment]
@torihoffmann looks good! You should add some checking for the length requirements for the username and other fields, though.

**Comment by torihoffmann** [comment]
okay can do! Didn't realize we needed a length requirement on those. I can def add that next time I work on this. Do you have any suggestions on what the length requirements should be. For now I'll do greater than or equal to 5 chars on username and gte 1 char on the rest since that is what you have specified on your write up, but should be pretty simple to change to whatever you think is best!

**Comment by eric-unc** [comment]
[The register doc](https://github.com/calendar-gang/tar-heel-calendar/blob/backend/docs/register.md) is all I'm checking on my end... as long as the username and similar fields are more than 1 character I'm fine :P

**Comment by eric-unc** [comment]
This issue seems resolved for now :)
